### SERVER
server:
  port: ${PORT:8080}

### SPRING
spring:
  application:
    name: DesafioCaju
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/caju}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

### SWAGGER
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    operationsSorter: method

### LOGGING
logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    com:
      example: TRACE

### ACTUATOR
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info
  info:
    env:
      enabled: true

### INFORMATION
info:
  app:
    name: "DesafioCaju"
    description: "DesafioCaju"
  author: "Pedro Estacio"
  java-version: ${java.version}

### APP CONFIGURATION
app:
  mcc:
    values:
      food: "5411,5412"
      meal: "5811,5812"